### PR TITLE
feat: Chinese Translation

### PR DESCRIPTION
**Pull request by 52fisher**

### CODE REVIEW

**Comment by pubpub-zz** [comment]
I have lots of trouble to see exactly your changes. I've guessed you've modified zh-cn1.txt. if so, can you attach the file apart in a comment please.

**Comment by 52fisher** [comment]
> 
> 
> I have lots of trouble to see exactly your changes. I've guessed you've modified zh-cn1.txt. if so, can yo[u attach the file apart in a comment please.

I just optimized some Chinese translations and added the translations of the "option" - "video"  tabs.
The translation of some words has been improved to be more suitable for Chinese expression, like  "笔迹" to "墨迹", "磁效应" to ""磁性吸附","截图" to “快照”. Reference to other software, Epic Pen/ PointFix/E-pointer/AxGlyph etc.
U can find more details in the link [Changes](https://github.com/pubpub-zz/ppInk/pull/29/files)
Anyway, could you  improve the user interface and icons ? Maybe it will make more users like it. It could be better.
I forked this repository and changed some icons last night, and It looks more modern now. 
图片
This repository has been translated into Chinese to to make more Chinese users use it . [52fisher](https://github.com/52fisher/ppInk
My English is not well, just some simple communication,and some expressions may not be correct.

**Comment by pubpub-zz** [comment]
I'm processing your translation zh-cn1.txt
can you tell me if it worth keeping zh-cn.txt I can't read chineese and have no idea wether it worth to keep both
I'm thinking about your new icons. how to handle that for the long term

**Comment by 52fisher** [comment]
zh-cn.txt is out. You can use zh-cn1.txt to take the place of zh-cn.txt.
I've got some icons from [iconfont](www.iconfont.cn), and the rest is my own design
For individuals, it's free.

**Comment by 52fisher** [comment]
Actually, I also have some ideas about the design that can improve the user experience. For example，
- When I press the Eraser button, the cursor can become an Eraser
- When I press ESC, I want the toolbar to be contracted and disable the drawing mode  (enable click-through mode) instead of just turning it off.
- Provides an option to adjust the size of the cursor,  which is too large。

**Comment by pubpub-zz** [comment]
> 
> 
> Actually, I also have some ideas about the design that can improve the user experience. For example，
> 
>     * When I press the Eraser button, the cursor can become an Eraser
> 
>     * When I press ESC, I want the toolbar to be contracted and disable the drawing mode  (enable click-through mode) instead of just turning it off.
> 
>     * Provides an option to adjust the size of the cursor,  which is too large。

There is some good ideas to think about. Can you raise a issue with those ideas

**Comment by pubpub-zz** [comment]
> 
>
> I've got some icons from [iconfont](https://www.iconfont.cn), and the rest is my own design
> For individuals, it's free.
The software is currently open for any use I would not like to introduce any limitation. I will think about a solution to allow any one to put its own icons then

**Comment by 52fisher** [comment]
> 
> 
> > I've got some icons from [iconfont](https://www.iconfont.cn), and the rest is my own design
> > For individuals, it's free.
> > The software is currently open for any use I would not like to introduce any limitation. I will think about a solution to allow any one to put its own icons then

Got it.Don't worry, I will design a set of icons that can be used freely as the default scheme for this software as quickly as possible.

**Comment by 52fisher** [comment]
done 
[new icons.zip](https://github.com/pubpub-zz/ppInk/files/5610253/new.icons.zip)

**Pull request closed without merging**
