### PR TITLE
DOC: add simplified version

### PR DESCRIPTION
**Pull request by earthjasonlin**
#230

### CODE REVIEW

**Comment by pubpub-zz** [comment]
@earthjasonlin,
thanks for your constructive proposal, I've added a few comments, can you review them before I can merge it.

**Comment by earthjasonlin** [comment]
I'm sorry but where are your comments...

**Review by pubpub-zz — COMMENTED** [review]
Can you see comments now?

**Comment by earthjasonlin** [comment]
> Can you see comments now?

Is that ok now

**Review by pubpub-zz — COMMENTED** [review]
Thanks for your contribution

**Review by pubpub-zz — APPROVED** [review]

**Pull request merged**
